### ISSUE TITLE
Checkbox for photo/recordings/video permissions

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#102]
Add a mandatory checkbox to the registration process asking for permissions to be included in photos/videos/recordings.

Make this configurable per conference.
Also ask this for registration of other people.
Also ask everyone who was registered by someone else to confirm this checkbox before accessing the ticket.

**Comment by detunjiSamuel** [comment]
If a conference has the photos/videos/recordings permissions active, does that mean it will be mandatory for people registering for the conference to accept the condition?

**Comment by dpage** [comment]
Yes. It's not feasible to figure out who gave consent and who didn't, and ensure they are edited out of any recordings or photos. Using red/blue lanyards is not foolproof even with the best of intentions, and we need to avoid the situation where a single person in the audience with a red lanyard prevents recording of session because the back of their head might be included, or they might face the camera whilst getting up to go to the toilet or something.

I think Ads' wording is a little off here; the intent is that it's more of a warning than a question, e.g.

I acknowledge and accept that images or videos might be recorded at the event that may include myself.

This doesn't mean that best efforts wouldn't be made to honour red lanyards; more an acknowledgement that the system isn't perfect.
