### ISSUE TITLE
Limit the amount of talks one person can submit

### ISSUE THREAD

**Issue by danielwestermann** [pgeu/pgeu-system#70]
Hi,

apparently it happened quite some times in the past, that a single person submitted more than 10 talks to a conference. We just have the case with 21 submissions from one single person. Can we please have an option to limit this, to maybe 4?  This puts unnecessary work on the talk selection committee.

Thanks in advance
Daniel

**Comment by mhagander** [comment]
This has been discussed in relation to a couple of conferences before, and the conclusion has always been that it's a bad idea.

However, that is not an argument against having the functionality in the system, as long as it's _optional_  (as suggested). Then everybody can choose for themselves.

So it would be worthwhile for someone to work on.

One thing to consider is what happens when speaker X adds speaker Y as a secondary speaker to their talk. We need to make sure we have a reasonable failure mode there, and that we don't end up building a denial-of-service path in there.

**Comment by danielwestermann** [comment]
I am not saying it needs to be mandatory, but an option would be great.

**Comment by andreasscherbaum** [comment]
Have this setting on the conference level is probably the best choice.

As for the secondary speaker: I don't believe that's really a problem. Maybe let's just look at primary speakers, and limit this number. For anything else this is still a case for the CfP Committee.
