### ISSUE TITLE
Count signed contracts in maximum number of sponsors

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#76]
Currently the number of sponsors is counted by "confirmed" status (as in: invoice is paid). This leaves a hole where a sponsor has signed the contract, it's countersigned and invoiced, but not fully confirmed.

Open sponsor slots should instead count against "Paid" and "Invoiced".

**Comment by mhagander** [comment]
Counted where? The normal counters I can find lists both Confirmed and Unconfirmed signups as separate numbers. If there is some place lacking that information, you need to actually point out where it is :)

**Comment by andreasscherbaum** [comment]
Counted when new sponsors want to sign up.

It's possible for new sponsors to sign up while all slots are taken by invoiced sponsors. Only when the sponsorship is paid then the slots count as taken.

**Comment by mhagander** [comment]
It's possible to sign up for *the waitlist* when that happens. The text, specifically, is (with example data):

```
This level allows a maximum of 3 sponsors. There are currently 2 confirmed and 1 unconfirmed sponsors signed up at this level. At this point, you can sign up on the wait list for this level, and will be granted a slot if not all other sponsors complete their signup. 
 ```
 
If that text needs clarification, then please suggest a new wording. To me it sounds pretty clear, so I'm not sure what to improve on it.

**Comment by andreasscherbaum** [comment]
Except that the sponsors are no longer unconfirmed. We consider them confirmed once we have a signed and countersigned contract.

This leads to sponsors trying to sign up for a higher level with hopes to get in, which at this point is unlikely (not impossible, but I don't think we ever had a sponsor cancel a signed contract). It would be easier if they know right away to go for another level.

Had this situation where all Platinum and Gold slots for the German conference were filled up, signed and invoiced, but some sponsors take longer to pay. For the time being the website shows that there might be slots available and someone has to go in, cancel the sponsorship request, explain to the sponsor what is going on.

**Comment by mhagander** [comment]
The system apparently works as it is intended to, and this workflow is based on many years of experience from pgconf.eu. This workflow is also (for once) actually documented.

If you want to suggest a different workflow, then by all means do so. But please suggest a complete workflow, and it should then be a choice on a per-conference basis, so as not to break things for others. Just changing the workflow that works for everybody else is not a productive way forward.

Also, it is clearly not an issue with the code if it works as intended, you just want a different feature. So please use the proper forum for discussing that rather than an issue, per previous agreements.

**Comment by andreasscherbaum** [comment]
I have no idea what "different workflow" you are talking about.

For pgconf.eu we currently (2022-05-10) have 3 Platinum sponsors. All three of them have a signed and countersigned contract, yet the website says:

```
This level allows a maximum of 4 sponsors. There are currently 1 confirmed and 2 unconfirmed sponsors signed up at this level.
```
Which by itself is misleading, if not plain wrong. After we signed and countersigned a sponsor contract, the sponsor is already confirmed and invoiced. We don't sign up additional sponsors beyond the limit (4) stated here, but until the sponsors have paid the invoice they still count as "unconfirmed" on the website and that opens the door for more sponsors to try to sign up. Since there is some wording about using bank transfers for higher sponsorship levels, and in general such a sum requires more and higher approval, it takes a few days until payment arrives.

Just because "we always did it this way" doesn't make it the best possible way, and it is still misleading.

**Comment by mhagander** [comment]
No that is not misleading, and it is most definitely not wrong. It's 100% correct: There *are* a maximum of 4 sponsors. There *is* 1 confirmed sponsor, and there *are* 2 unconfirmed sponsors. By the exact definition of what confirmed and unconfirmed means.

And no, once they are confirmed, they do not count as unconfirmed. This is a boolean field in the database. The payment is a *separate* step and not part of the confirmation step. This is also documented.

And no, we did not always do it this way: We changed it to this way because the previous way caused a lot of issues.

Again, what's there now works exactly as intended and exactly as documented. And if you want to change those, you need to make an actual proposal of a complete change and not just say "count it differently".

**Comment by andreasscherbaum** [comment]
To close this one out: I went back into notes and emails, and this is a result of a board meeting which requested a way to have a manual confirmation for each sponsor. There was never a discussion about what is shown on the website to the sponsor, or how sponsors are counted. For a new sponsor it doesn't matter if other sponsors have already paid or not, they can simply not know. It also doesn't matter if that is documented, what counts is if a sponsor has a realistic chance to signup on the specific level - and that chance is close to zero once all slots are taken by other sponsors, signed contracts exist and invoices are generated. The fact that an invoice is not yet paid is an internal detail only relevant to the organizer.

The current form which counts sponsors the way it is today came in with commit e57991e473fb00816e2cc06afd5ee8e4dd046015 (the sponsor waitlist feature), committed Nov 6 2018 (after pgconf.eu in Lisbon), and was at scale only ever applied for Milan in 2019.

Looking at the timeline how sponsors signed up for Milan, we had one Platinum sponsor signing up quite late, but at this time there were also 2 Gold available. And when the two Gold filled up, the Platinum were all confirmed already. There has not been an issue where sponsors could have been confused by the fact that other sponsors are signed up but haven't paid yet.
