### ISSUE TITLE
Disallow multiple parcels in one shipment

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#81]
Handling a room full of parcels and trying to find every parcel which belongs to a multi-shipment with the same refcode is a huge mess. It would be much easier if sponsors are forced to create different shipment codes for each parcel, so we can tick them off one by one. In turn this also helps to track what is in each shipment and where it is supposed to be used for.

**Comment by mhagander** [comment]
This seems like a terrible idea. Doing it that way will now make it impossible for sponsors to ship things directly from a vendor, since they are highly unlikely to be able to dictate such a requirement to the vendor.

Based on that a strong -1 from me. But if you still think it's a good idea, please make sure you make it in a way that makes it configurable on a per-conference basis and default to off, so that others can still use it :)

**Comment by danielgustafsson** [comment]
Maybe we can solve this with documentation? If conferences who want separate shipping stress the importance of that in their communication with sponsors it might work itself out without having to change anything?

**Comment by andreasscherbaum** [comment]
As Magnus pointed out repeatedly today: people don't read. Either we get the workflow into a way which guides them into what we need, or we have to deal with the result.

**Comment by danielgustafsson** [comment]
> As Magnus pointed out repeatedly today: people don't read. Either we get the workflow into a way which guides them into what we need, or we have to deal with the result.

In that case then I vote for having it be a per-conference setting.

**Comment by andreasscherbaum** [comment]
Which does not solve any problem? But I keep hearing this as well.

**Comment by danielgustafsson** [comment]
> Which does not solve any problem? But I keep hearing this as well.

I'm not sure I follow. Why won't it solve the problem if you can have the feature that you want to have?

**Comment by andreasscherbaum** [comment]
Sorry, I meant that I heard "make it configurable per conference" way too many times before.
Then the problem still exists and no one thought about how to improve the entire process, but instead just keep it as it is.

**Comment by mhagander** [comment]
There are others who don't think it's actually a problem, or at least that doing this would make it a smaller problem. Making it configurable would allow the people running each conference to prioritize which behavior they prefer.

Like, per above, if this is not made configurable I will very strongly object to the idea of implementing this at all.

**Comment by mhagander** [comment]
Reading through this again, it's pretty clear this is not going to work.

There is no way to force sponsors to not send more than one box. What we can do is remove the field that says how many boxes. But if the assumption is that sponsors don't read the instructions, then they will still ship more boxes.

So while it does not solve the actual problem reported, it also still breaks for the scenario for example where the sponsors orders directly from a vendor and cannot do it. So it's purely negative, with no actual win.

And I agree that doing this on a per-conference basis isn't going to help -- since it doesn't actually solve the problem in the first place, not solving it for just certain conferences isn't an improvement.

To solve the actual problem mentioned in the OP, a broader redesign of the workflow would be needed. Thus, I'm going to go ahead and close this issue until such a proposal exists. And until then, those who actually believe the current workflow works reasonably well, can keep on using it.
