### ISSUE TITLE
Link to Speaker Profile is "Not Found" when the user has no speaker profile

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#85]
When the user has no speaker profile, but is sent to a link with a speaker profile, this results in a "Not Found" error.

* https://www.postgresql.eu/events/pgconfeu2022/speakerprofile/
* https://www.postgresql.eu/events/speakerprofile/

If the user goes to [Call for Papers](https://www.postgresql.eu/events/callforpapers/), a link to fill out the speaker profile is presented. This should also happen when the user arrives at the links above.

**Comment by mhagander** [comment]
This seems to come out of a simple thinko -- there's code in there to handle this case, but it was catching the wrong exception vs the one actually created. This seems to have been, ahem, broken since the original code in 2010.

This may also partially explain the many cases of people submitting a talk without filling out their speaker profile.

Good catch!
